from __future__ import annotations

import sys
from pathlib import Path
from typing import Dict, Optional

import pandas as pd
import streamlit as st
import torch

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from inference.compare_models import discover_models
from inference.generate import load_generator
from utils.io import BENCHMARKS_DIR, COMPARISONS_DIR, resolve_fast_checkpoint, resolve_quality_checkpoint
from utils.metrics import save_image_grid
from utils.seed import set_seed


def available_models() -> Dict[str, Path]:
    return {name: path for name, path in discover_models()}


def model_type_label(model_name: str) -> str:
    if model_name == "baseline":
        return "Dense baseline generator"
    if model_name.startswith("pruned") or model_name == "best_pruned":
        return "Pruned compressed generator"
    if model_name == "quantized":
        return "Quantized compressed generator"
    return "Generator variant"


def human_model_name(model_name: str) -> str:
    mapping = {
        "baseline": "Baseline",
        "best_pruned": "Best Pruned",
        "pruned_20": "Pruned 20%",
        "pruned_40": "Pruned 40%",
        "pruned_60": "Pruned 60%",
        "quantized": "Quantized",
    }
    return mapping.get(model_name, model_name.replace("_", " ").title())


def tradeoff_note(model_name: str) -> str:
    notes = {
        "baseline": "Highest visual quality among the available variants, but also the largest and least compressed.",
        "pruned_20": "Light compression with a small expected quality drop and modest efficiency gain.",
        "pruned_40": "Moderate compression with a clearer speed-size benefit and a moderate quality drop.",
        "pruned_60": "Aggressive compression with stronger artifacting risk and more visible visual degradation.",
        "best_pruned": "Best compressed quality checkpoint selected from the pruning sweep for practical deployment balance.",
        "quantized": "Smallest artifact and usually the cheapest to store, but samples may look blurrier or lower contrast.",
    }
    return notes.get(model_name, "Prototype model variant for edge deployment comparison.")


def output_explanation(model_name: str) -> str:
    if model_name == "baseline":
        return (
            "This output is generated by the baseline dense model. It is the quality reference for this demo, "
            "so it is expected to preserve the strongest visual structure while using more memory and model size."
        )
    if model_name == "quantized":
        return (
            "This output is generated by the quantized model artifact. It prioritizes deployment efficiency and "
            "storage reduction, so some blur or contrast loss is expected compared with the baseline."
        )
    return (
        "This output is generated by a compressed model variant. Compression reduces deployment cost, but it can "
        "soften edges, weaken garment structure, or increase visible noise in the synthetic samples."
    )


def selection_reason(mode: str, active_model_name: str, checkpoint_name: str) -> str:
    if mode == "quality":
        return (
            f"Quality mode selected `{checkpoint_name}` as the baseline checkpoint because the latency budget allows "
            "higher-quality inference and the demo prioritizes the strongest available visual output."
        )
    return (
        f"Fast mode selected `{checkpoint_name}` as the compressed runtime target because low-latency, lower-memory "
        f"inference is prioritized over visual fidelity. The active fast variant is `{active_model_name}`."
    )


def path_to_model_name(path: Path, models: Dict[str, Path]) -> str:
    for name, candidate in models.items():
        if candidate == path:
            return name
    if "quantized" in path.name:
        return "quantized"
    if "pruned_20" in path.name:
        return "pruned_20"
    if "pruned_40" in path.name:
        return "pruned_40"
    if "pruned_60" in path.name:
        return "pruned_60"
    if "best_pruned" in path.name:
        return "best_pruned"
    return "baseline"


def display_path_label(path: Path) -> str:
    if path == resolve_quality_checkpoint():
        return f"{path.name} (baseline / quality)"
    if path == resolve_fast_checkpoint():
        return f"{path.name} (adaptive fast target)"
    return path.name


def benchmark_dataframe() -> Optional[pd.DataFrame]:
    results_path = BENCHMARKS_DIR / "results.csv"
    if not results_path.exists():
        return None
    df = pd.read_csv(results_path)
    rename_map = {
        "model_name": "Model",
        "model_size_mb": "Size (MB)",
        "avg_latency_ms": "Latency (ms)",
        "throughput_samples_per_sec": "Throughput",
        "peak_memory_mb": "Peak Memory",
        "visual_quality_note": "Quality Note",
    }
    df = df.rename(columns=rename_map)
    keep_columns = ["Model", "Size (MB)", "Latency (ms)", "Throughput", "Peak Memory", "Quality Note"]
    df = df[[column for column in keep_columns if column in df.columns]]
    return df


def render_sidebar(models: Dict[str, Path]) -> tuple[str, int, str]:
    comparison_choices = list(models.keys())
    baseline_index = comparison_choices.index("baseline") if "baseline" in comparison_choices else 0
    mode = st.radio("Inference mode", ["quality", "fast"], horizontal=True)
    control_columns = st.columns([1, 1, 1])
    num_samples = control_columns[0].slider("Number of samples", 4, 16, 8, step=4)
    spotlight_model = control_columns[1].selectbox("Comparison spotlight", comparison_choices, index=baseline_index)
    control_columns[2].info(
        "Use `quality` to show the baseline reference. Use `fast` to show the compressed deployment target."
    )
    return mode, num_samples, spotlight_model


def render_overview() -> None:
    st.title("EdgeGen")
    st.caption("Edge-Deployable Generative AI with Compression and Adaptive Inference")
    st.write(
        "This prototype studies how a lightweight generative model behaves under edge constraints. "
        "It compares baseline, pruned, and quantized versions of the same generator and shows the "
        "tradeoff between image quality, latency, memory, and model size."
    )

    with st.expander("Research Abstract", expanded=False):
        st.write(
            "EdgeGen is a research-style prototype for studying generative AI under edge deployment constraints. "
            "The system trains a small DCGAN on Fashion-MNIST, then evaluates how pruning and quantization affect "
            "runtime efficiency and sample quality on CPU hardware. The dashboard presents dense, pruned, and "
            "quantized variants of the same generator so that visual fidelity can be interpreted alongside latency, "
            "memory use, throughput, and model size. An adaptive inference controller switches between a higher-quality "
            "baseline model and a faster compressed model according to runtime budget. Because the dataset is small and "
            "the model is intentionally lightweight, samples are prototype-level and may appear blurry or noisy. "
            "The goal is not state-of-the-art synthesis, but a clear systems demonstration of the quality-efficiency "
            "tradeoff that edge generative AI must manage in practice."
        )

    with st.expander("Demo Guide", expanded=False):
        st.markdown(
            "- Click `quality` first to view the baseline reference output.\n"
            "- Switch to `fast` to see how adaptive inference chooses the compressed runtime model.\n"
            "- Compare the labeled model cards to inspect how compression changes sample sharpness and structure.\n"
            "- Read the benchmark table to connect visual changes with latency, memory, and model size.\n"
            "- The intended conclusion is that edge deployment gains efficiency through compression, but visual fidelity usually decreases."
        )


def render_problem_statement() -> None:
    st.header("Problem Statement")
    st.info(
        "Generative AI models are powerful, but they are often expensive to run. Edge devices such as mobile or "
        "embedded systems have limited memory, compute, and energy. Compression can make these models easier to deploy, "
        "but that usually reduces output quality. EdgeGen demonstrates that tradeoff directly."
    )


def render_how_to_read() -> None:
    st.header("How To Read This Demo")
    st.markdown(
        "- `Quality mode` = best baseline model, better output quality, higher cost.\n"
        "- `Fast mode` = compressed model, faster inference, lower memory, lower quality.\n"
        "- `Baseline` = original dense generator.\n"
        "- `Pruned` = sparse compressed generator.\n"
        "- `Quantized` = low-precision compressed generator.\n"
        "- Generated samples are synthetic Fashion-MNIST-like outputs, not real images.\n"
        "- Because the model is small and the dataset is tiny (28x28 grayscale), outputs may look blurry or noisy."
    )


def render_selection_summary(
    mode: str,
    spotlight_model: str,
    num_samples: int,
    active_model_name: str,
    selected_path: Path,
    load_mode: str,
) -> None:
    st.header("Current Selection")
    cards = st.columns(6)
    cards[0].metric("Inference Mode", mode.title())
    cards[1].metric("Displayed Model Version", human_model_name(active_model_name))
    cards[2].metric("Checkpoint", selected_path.name)
    cards[3].metric("Runtime Load Mode", load_mode)
    cards[4].metric("Samples", str(num_samples))
    cards[5].metric("Comparison Spotlight", human_model_name(spotlight_model))
    st.success(selection_reason(mode, human_model_name(active_model_name), selected_path.name))


def render_generated_output(
    mode: str,
    active_model_name: str,
    selected_path: Path,
    load_mode: str,
    num_samples: int,
) -> None:
    st.header("Main Generated Output")
    generator, _ = load_generator(selected_path)
    generator.eval()
    with torch.no_grad():
        images = generator.sample(num_samples, "cpu")

    grid_path = BENCHMARKS_DIR / "streamlit_preview.png"
    save_image_grid(images, grid_path, title=f"{selected_path.stem} ({load_mode})", nrow=4)
    st.image(str(grid_path), caption=f"Live output from {display_path_label(selected_path)}")
    st.write(output_explanation(active_model_name))

    if mode == "quality":
        st.caption(
            "This is the baseline / quality model. It is expected to look strongest visually, but it uses more model "
            "capacity and therefore less compression."
        )
    else:
        st.caption(
            "This is the fast inference path. It emphasizes lower deployment cost and faster runtime, even if the "
            "samples become noisier, blurrier, or less consistent."
        )


def comparison_card(column, model_name: str, models: Dict[str, Path]) -> None:
    column.subheader(human_model_name(model_name))
    column.caption(model_type_label(model_name))
    image_path = COMPARISONS_DIR / f"{model_name}_grid.png"
    if image_path.exists():
        column.image(str(image_path), use_container_width=True)
    else:
        if model_name == "quantized":
            column.info("Quantized comparison image is unavailable. Run quantization and `python inference/compare_models.py`.")
        else:
            column.info("Comparison image not found yet. Run `python inference/compare_models.py` to populate this card.")
    column.write(tradeoff_note(model_name))
    if model_name in models:
        column.caption(f"Artifact: `{models[model_name].name}`")


def render_comparison(models: Dict[str, Path]) -> None:
    st.header("Model Comparison")
    st.write("All comparison outputs below use the same latent vectors so the visual differences are fair.")

    combined_path = COMPARISONS_DIR / "combined_comparison.png"
    summary_path = COMPARISONS_DIR / "comparison_summary.md"
    if combined_path.exists():
        st.image(str(combined_path), caption="Shared-latent comparison across model variants")
    else:
        st.info("Comparison outputs not found yet. Run `python inference/compare_models.py` to populate this section.")

    names = ["baseline", "pruned_20", "pruned_40", "pruned_60", "quantized"]
    for start in range(0, len(names), 2):
        row = st.columns(2)
        for column, model_name in zip(row, names[start : start + 2]):
            comparison_card(column, model_name, models)

    if summary_path.exists():
        st.download_button(
            "Download comparison summary",
            data=summary_path.read_text(),
            file_name="comparison_summary.md",
            mime="text/markdown",
        )


def render_performance_summary() -> None:
    st.header("Performance Summary")
    st.write("This table summarizes the efficiency-quality tradeoff across model variants.")
    df = benchmark_dataframe()
    if df is None:
        st.info("Benchmark results not found yet. Run benchmark/benchmark.py to populate this section.")
        return
    st.dataframe(df, use_container_width=True, hide_index=True)


def render_takeaways() -> None:
    st.header("Key Takeaways")
    st.success(
        "Compression reduces model size and latency. Stronger compression often reduces visual fidelity. "
        "Adaptive inference can choose between quality and efficiency depending on runtime budget. "
        "This prototype demonstrates a practical edge AI tradeoff for generative models."
    )


def render_limitations() -> None:
    st.header("Limitations")
    st.markdown(
        "- Fashion-MNIST is a small grayscale benchmark dataset.\n"
        "- Generated samples are prototype-level outputs.\n"
        "- This is not a large-scale image generator.\n"
        "- Quality evaluation is lightweight and not full FID-scale research benchmarking.\n"
        "- The goal is system demonstration, not state-of-the-art image synthesis."
    )


def render_future_work() -> None:
    st.header("Future Work")
    st.markdown(
        "- Layer-specific pruning.\n"
        "- Low-data generative training.\n"
        "- Diffusion-based edge generation.\n"
        "- Real deployment on Raspberry Pi / Jetson.\n"
        "- Better quantitative quality metrics."
    )


def main() -> None:
    st.set_page_config(page_title="EdgeGen Demo", layout="wide")
    set_seed(42)
    models = available_models()

    render_overview()

    if not models:
        st.error("No model artifacts found. Run training and compression first.")
        render_problem_statement()
        render_how_to_read()
        render_limitations()
        render_future_work()
        return

    st.header("Demo Controls")
    mode, num_samples, spotlight_model = render_sidebar(models)
    selected_path = resolve_quality_checkpoint() if mode == "quality" else resolve_fast_checkpoint()
    active_model_name = path_to_model_name(selected_path, models)
    _, load_mode = load_generator(selected_path)

    render_problem_statement()
    render_how_to_read()
    render_selection_summary(mode, spotlight_model, num_samples, active_model_name, selected_path, load_mode)
    render_generated_output(mode, active_model_name, selected_path, load_mode, num_samples)
    render_comparison(models)
    render_performance_summary()
    render_takeaways()
    render_limitations()
    render_future_work()


if __name__ == "__main__":
    main()
